### ISSUE TITLE
[BUG] Flakey cypress test

### ISSUE THREAD

**Issue by leeyun-amzn** [opensearch-project/alerting-dashboards-plugin#106]
**Describe the bug**
The following cypress test is flakey:
```
 1) Bucket-Level Monitors
       can be created
         by extraction query:
     AssertionError: Timed out retrying after 10000ms: Expected to find content: 'This table contains 1 row' but never did.
      at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/bucket_level_monitor_spec.js:319:10)
 ```
 
 Should update the assertion to something more stable.

**To Reproduce**
1. Run `yarn run cypress open` or `yarn run cypress run` along with OpenSearch and OpenSearch dashboard in background. (Detailed instructions in README or documentation)
2. Check the "Bucket-Level Monitors can be created by extraction query" cypress test. If not failing, try a few more times.

**Expected behavior**
Will see the error `AssertionError: Timed out retrying after 10000ms: Expected to find content: 'This table contains 1 row' but never did.`

**Host/Environment (please complete the following information):**
 - Version 1.1.0

**Comment by AWSHurneyt** [comment]
Closing this issue as it was resolved with [this PR](https://github.com/opensearch-project/alerting-dashboards-plugin/pull/135).
