### ISSUE TITLE
[BUG] Visual Editor Monitor is saved as Extraction Query Monitor

### ISSUE THREAD

**Issue by xluo-aws** [opensearch-project/alerting-dashboards-plugin#1123]
**What is the bug?**
I'm testing on future playground with a remote data source using 2.17.1 version. Create a visual editor monitor but it's saved as Extraction Query monitor. Main has the same issue

**How can one reproduce the bug?**
1. Go to '[...](https://future.playground.opensearch.org/)'
2. Select a workspace with Alert feature
3. Create a monitor using visual editor
4. Once the monitor is created,  the monitor definition type becomes Extraction query.

**What is the expected behavior?**
The monitor definition type should remain as visual editor

**What is your host/environment?**
 - Version [OS2.17.1]
 - Plugins [Alert]

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by AWSHurneyt** [comment]
@xluo-aws I wasn't able to reproduce the issue using the playground link you provided above. I created `hurneyt-test` monitor which shows `visual graph` on the details page, and the edit page shows the visual editor display.
<img width="669" alt="Screenshot 2024-10-10 at 11 58 55 AM" src="https://github.com/user-attachments/assets/756a7720-2c87-4985-a71d-646810bc9644">
![Screenshot 2024-10-10 at 12 00 05 PM](https://github.com/user-attachments/assets/4c6096d8-b180-45c6-8db7-0461a0b07ab7)

**Comment by AWSHurneyt** [comment]
I was able to reproduce the issue in the playground link provided above by adjusting the workspace/datasource. Troubleshooting now.

**Comment by songkant-aws** [comment]
Backend that ui_metadata is probably excluded based on 'User-Agent' header: https://github.com/opensearch-project/alerting/blob/main/alerting/src/main/kotlin/org/opensearch/alerting/util/RestHandlerUtils.kt#L20-L25.
The backend only includes ui_metadata only if the node server requests to opensearch 'User-Agent' header contain 'Opensearch-Dashboards'. However, MDSClient may not have it.
