### ISSUE TITLE
[BUG] Bulk acknowledge alerts only works for first 10 alerts in a trigger

### ISSUE THREAD

**Issue by leeyun-amzn** [opensearch-project/alerting-dashboards-plugin#126]
**Describe the bug**
On alerts by triggers page, when acknowledging alerts from 1 trigger it only applies to the first 10 alerts. 

**To Reproduce**
1. Create a bucket-level monitor with 10+ alerts in 1 trigger. (Try using  sample ecommerce data with count of documents below 10000 over the past 3 days) 
2. Click on Alerts tab
3. Select the trigger with more than 10+ alerts.
4. Click the "Acknowledge" button. 
5. Should see that "Active" column only decreased by 10, and "Acknowledged" column only adds 10. 

**Expected behavior**
All alerts within the trigger should be acknowledge. If error occurs, should show an error notification. 

**Screenshots**
N/A

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by AWSHurneyt** [comment]
Closing this issue as it was resolved with [this PR](https://github.com/opensearch-project/alerting/pull/210).
