### ISSUE TITLE
Error toast when creating a monitor for the first time

### ISSUE THREAD

**Issue by ohltyler** [opensearch-project/alerting-dashboards-plugin#172]
On a fresh cluster, before all of the plugin system indices have been inited, there is an error toast that shows up in the unified flow when creating a monitor with a trigger:

![Screen Shot 2022-02-10 at 4 02 15 PM](https://user-images.githubusercontent.com/62119629/153518844-3cc41358-d3f0-4696-a588-af279a69b77d.png)

These types of errors should be caught and handled. AD has a solution of filtering out the type of exception being faced, and ignoring if applicable (e.g., loading the detector list page without the `.opendistro-anomaly-detectors` system index present). See [here](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/blob/main/server/routes/ad.ts#L492-L494) for details

**Comment by ohltyler** [comment]
@lezzago can confirm, but this change may need to be backported to versions older than 1.3.

**Comment by lezzago** [comment]
Fixed in main: https://github.com/opensearch-project/alerting-dashboards-plugin/pull/173

@ohltyler to your question, we typically dont backport for older releases, but this can be considered and will leave this open
