### ISSUE TITLE
[BUG] Issues in the UI above 200 destinations

### ISSUE THREAD

**Issue by jbgachot** [opensearch-project/alerting-dashboards-plugin#195]
**Describe the bug**
I currently have more than 200 destinations in the alerting plugin and issues are noticeable : 

 - In the "Destinations" list, pagination above item 200 is broken : 
   - number of page is correct
   - if you click on a page representing an item above 200, you can quickly see the correct page but then you are redirected back to the page that is not bugged
  
- In the "Create monitor" page : 
 - if you create an action, the destination except the first 200 are not listed in the UI and you can't select them

**To Reproduce**
1. Create more than 200 destinations
2. Go to '/app/alerting#/destinations'
3. Play with the pages (1)
4. Create a monitor and a trigger
5. Start typing a destination that is not in the 200 firsts (2), it's missing

**Plugins**
Default install (everything)

**Host/Environment**
 - OS: Debian
 - Version: 10

Opensearch Dashboards 1.2.0

**Comment by jbgachot** [comment]
One more detail : 
 - I stated that `number of page is correct` but it is actually correct on the top page pagination, but the pagination at the bottom of the page "destinations" is stuck to the virtual size of 200 divided by the number of item per page, and don't show up pages above.

**Comment by amsiglan** [comment]
Fixed for 2.x and 1.x, so this will make it in next patch release and ahead
