### ISSUE TITLE
[BUG] Period (.) at the beginning or end of a trigger name resets trigger conditions when editing monitor

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/alerting-dashboards-plugin#203]
**Describe the bug**
Having a `.` at the beginning or end of a trigger name causes the trigger condition values to reset when editing the monitor in the UX. 

**To Reproduce**
1. Go to `Create monitor`
2. Define a `Per query monitor`
3. Create a trigger with a name that includes a `.` as the first or last character; e.g., `.trigger` or `trigger.`
4. Create the monitor
5. Go to the edit monitor page
6. The trigger condition will reset to the default values of `IS ABOVE 10000`

**Expected behavior**
The UX should display the configured trigger condition; not the defaults.

**Plugins**
`Alerting` and `alertingDashboards`.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: IOS
 - Version 10.15.7 

**Additional context**
Related issues from the ODFE alerting plugin repo:
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/152
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/199
https://github.com/opendistro-for-elasticsearch/alerting-kibana-plugin/issues/207

**Comment by AWSHurneyt** [comment]
`Per bucket monitors` do not seem to have this same issue.

**Comment by AWSHurneyt** [comment]
Tracked the issue to `formikToTrigger::formikToTriggerUiMetadata`and `triggerToFormik::queryLevelTriggerToFormik`. 

The `_set()` call on line `153` in `formikToTriggerUiMetadata` was removing the `.`s at the ends of the trigger name in the `uiMetadata`. In addition, the `_.get()` calls starting at line `49` in `queryLevelTriggerToFormik` were not factoring the `.` into their logic. This is likely due to the dot notation used for the `path` parameter of the `_.get()` and `_.set()` functions.

Implemented a fix that passes testing using trigger names like `.trigger`, `trigger.`, `..trigger..`, and `.trigger.name.`.

**Comment by dblock** [comment]
Is this fixed @AWSHurneyt, still 2.0?

**Comment by AWSHurneyt** [comment]
> Is this fixed @AWSHurneyt, still 2.0?

Yes, just merged the fix in today. I'll close this issue.
