### ISSUE TITLE
Bump the version for 1.3.1 opensearch-dashboards release

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/alerting-dashboards-plugin#206]
**Is your feature request related to a problem? Please describe.**
We need to bump the version for 1.3.1 in 1.x and 1.3 branches for 1.3.1 releases wrt to the release issue - https://github.com/opensearch-project/opensearch-build/issues/1885

**Comment by abhinavGupta16** [comment]
@charliezhangaws - Do we need this PR - https://github.com/opensearch-project/alerting-dashboards-plugin/pull/208?

cc: @bbarani @CEHENKLE @kavilla

**Comment by kavilla** [comment]
I think 208 accidentally merges main into 1.3

**Comment by lezzago** [comment]
I have closed that PR. It was incorrect since it merges in main changes and #207 is already merged
