### ISSUE TITLE
[BUG] Can configure multiple indices for a document level monitor

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/alerting-dashboards-plugin#258]
**What is the bug?**
Document level monitors currently only support being configured with 1 index; however, the UI can be used to bypass that limitation. The monitor will still fail to execute with the following error message: `Failed to start Document-level-monitor. Error: Only one index is supported with document-level-monitor.`

**How can one reproduce the bug?**
1. Go to the `Create` or `Edit` monitor page
2. Select the `Per document monitor` type option
3. In the `Index` field, select an index from the list, or type in an index name, and press `Enter`. You can then type in another index name, and press `Enter` again to add it to the list

**What is the expected behavior?**
The UI should not allow users to configure a document level monitor with multiple indices.

**What is your host/environment?**
 - OS: iOS
 - Version 10.15.7
 - Plugins `alerting`, `alerting-dashboards-plugin`

**Do you have any screenshots?**
This screenshot what it looks like when multiple indices have been configured.
![Screen Shot 2022-06-02 at 2 16 55 PM](https://user-images.githubusercontent.com/79280347/171741483-52fcbaad-bd0b-469a-a899-03c24d25fbb1.png)

This screenshot shows what the monitor JSON payload looks like in this scenario. No error is thrown because the list of indices are formatted correctly according to the validation.
![Screen Shot 2022-06-02 at 2 17 10 PM](https://user-images.githubusercontent.com/79280347/171741659-33cb0113-ffd9-4105-ac83-99c573fffb3d.png)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by amsiglan** [comment]
@AWSHurneyt Should we close this bug?
