### ISSUE TITLE
[BUG] [Alerting Plugin] Error when adding notification to monitor

### ISSUE THREAD

**Issue by pietrogu** [opensearch-project/alerting-dashboards-plugin#270]
**Describe the bug**

After updating to 2.0.0, when i try to create or update a monitor I receive the following error

`[illegal_state_exception] Can't get text on a START_OBJECT at 1:10320`

I discovered that this happens when i add an action to a trigger. In particular, I tried to add a mail notification action

**To Reproduce**
1. Create monitor
2. Add a trigger
3. Add an action to the trigger selecting a mail type channel

**Expected behavior**
The update or the creation of the monitor should go as planned.

**OpenSearch Version**
2.0.0
**Dashboards Version**
2.0.0

**Plugins**

Alerting
Notifications

**Screenshots**

This is the error in Dashboards GUI
<img width="260" alt="image" src="https://user-images.githubusercontent.com/52070642/173099577-6287305a-a056-4f2a-b61a-82f4226a01f6.png">

This is the corresponding log
<img width="778" alt="image" src="https://user-images.githubusercontent.com/52070642/173100700-10b5ee02-6b8f-48c2-a885-9a8d52fff645.png">

**Host/Environment (please complete the following information):**
 - Docker

**Comment by pietrogu** [comment]
Hi @kavilla 

thank you, in the next days i'll try the workaround. If it works i'll close the issue.

Regards,
Pietro

**Comment by lezzago** [comment]
Closing in favor of #254
