### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/alerting-dashboards-plugin#290]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @praveensameneni @qreshi, can you please post an update on this branching alignment?
@bbarani @CEHENKLE @bbarani

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by bbarani** [comment]
@qreshi Are we good to target this change for 2.4.0 release?

**Comment by qreshi** [comment]
This was blocked for some time since Alerting backend couldn't bump because Notifications couldn't get to 3.0. This has since been unblocked so if Alerting backend `main` is on `3.0`, then we should bump Alerting OSD `main` and then we can close this out.

**Comment by bbarani** [comment]
@qreshi Can you provide updated status of this issue?

**Comment by qreshi** [comment]
@lezzago and @AWSHurneyt may have a more up-to-date picture here. I saw that the Alerting backend was bumped to 3.0 yesterday so the frontend will likely soon follow.

**Comment by bbarani** [comment]
@AWSHurneyt @qreshi Whats the status of this issue?

**Comment by AWSHurneyt** [comment]
> @AWSHurneyt @qreshi Whats the status of this issue?

I believe all that's missing at the moment is that the `main` branch is not currently set to version `3.0`. There were some failures in the bump PR which I have on my tasks list to investigate.

**Comment by bbarani** [comment]
@AWSHurneyt Can you please provide an update? Were you able to bump the version on main to 3.0?

**Comment by AWSHurneyt** [comment]
> @AWSHurneyt Can you please provide an update? Were you able to bump the version on main to 3.0?

The `main` branch hasn't been bumped yet, but I'm planning to investigate the blockers for that this sprint.
