### ISSUE TITLE
[BUG] Alert details flyout's responsiveness

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/alerting-dashboards-plugin#296]
**What is the bug?**
The table and the push flyout do not resize gracefully in the `Alerts by triggers` list in the Alerting plugin for different screen sizes:
1. The elements in the table header don't stack but move outside of the table
2. On the smaller screens the table becomes unusable
3. On the screens smaller than about 990px the flyout switches to overlay type overlapping and blocking the table.
4. The monitor name is truncated even if there is enough space to accommodate the full name

**How can one reproduce the bug?**
Steps to reproduce the behavior (assuming the `Alerts by triggers` table is not empty):
1. Go to the 'Alerting' plugin - this will land you on `Alerts by triggers` page
5. Click on the "burger" icon in the top left corner of the screen
6. Click on the last item in the main navigation panel `Dock navigation`
7. Click on the number of alerts in the second column of the table - the flyout appears in the right part of the screen and resizes the table
8. Resize the browser window to less than ~1700px
9. Then change the size of your browser window to less than ~990px

**What is the expected behavior?**
All elements of the table should resize gracefully. The push flyout width/proportion should adjust to the screen size. 
On the screens smaller than ~990px the overlay type flyout should not obscure the table (By setting `ownFocus={false}`, the underlying page content will be visible and clickable.). The monitor name column should be wider when screen size permits to show the names of the monitors without truncation.

**What is your host/environment?**
 - OS: macOS
 - Version 12.4
 - Plugins `Alerting`
 - Browser `Chrome`, `Firefox`, `Safari`

**Do you have any screenshots?**
<img width="1109" alt="Screen Shot 2022-08-03 at 11 30 42 PM" src="https://user-images.githubusercontent.com/105245012/182779047-3089d971-613e-4780-a276-c4d65c665753.png">

<img width="950" alt="Screen Shot 2022-08-03 at 11 31 00 PM" src="https://user-images.githubusercontent.com/105245012/182779052-bcc3f30e-7cf8-4397-b38c-449c805b5937.png">

<img width="862" alt="Screen Shot 2022-08-03 at 11 31 26 PM" src="https://user-images.githubusercontent.com/105245012/182779055-56a499f2-c10f-4aec-97d9-ec014dd39d63.png">

<img width="1636" alt="Screen Shot 2022-08-03 at 11 28 56 PM" src="https://user-images.githubusercontent.com/105245012/182779035-b47298f0-9148-4b3e-9273-47927f8b3682.png">

<img width="1859" alt="Screen Shot 2022-08-04 at 12 03 42 AM" src="https://user-images.githubusercontent.com/105245012/182784858-94b3f663-6592-442e-8f1b-0ffd6a9f414e.png">

**Do you have any additional context?**
The problems with responsiveness seem to be amplified by introducing the `dock navigation` feature in the main menu in combination with the push flyout use. The `pushMinBreakpoint` for the overlay flyout might need to be reviewed along with the docked navigation behavior for the small screens.

**Comment by AWSHurneyt** [comment]
Good catch; there are a few elements that don't seem to resize gracefully. I'll look into this.
