### ISSUE TITLE
[BUG] Click on a table row closes the flyout with monitor details instead of opening another one for a different alert

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/alerting-dashboards-plugin#299]
**What is the bug?**
Click on Alerts by trigger entry in the table opens a flyout with monitor detailed information. If user wants to navigate to another monitor' details without closing the flyout, they would click on another entry in the table. This causes the initially opened flyout to close instead of replacing it.

**How can one reproduce the bug?**

1. Go to `Alerting`
2. Click on any entry in the `Alerts by trigger` table (assuming that the table is populated)
3. See the flyout with monitor details
4. Click on any other entry in the table
5. See the flyout closed

**What is the expected behavior?**
A click on the table entry should open a flyout with the monitor details. If another flyout is already present on the screen, the first one should be closed and the second one opened automatically. Closing the flyout is triggered by the controls in the flyout itself and by clicking outside of the table on the main screen.

**What is your host/environment?**

- OS: macOS
- Version 12.4
- Plugins Alerting
- Browser Chrome, Firefox, Safari

**Comment by AWSHurneyt** [comment]
Fixed this issue locally on the `Alerts by trigger` table, but noticed that it also exists on the monitor details page for document level monitors. Looking into a solution for that before submitting the fix.

**Comment by amsiglan** [comment]
No longer relevant as we moved to using overlay type of flyouts.
