### ISSUE TITLE
[BUG] The "X" (close) icon is missing from the monitor details flyout

### ISSUE THREAD

**Issue by xeniatup** [opensearch-project/alerting-dashboards-plugin#300]
**What is the bug?**
The "X" (close) icon is missing from the monitor details flyout's top right corner, which creates inconsistency in the flyout behavior and disrupts the flow for user.

**How can one reproduce the bug?**
1. Go to `Alerting`
2. Land on `Alerts by trigger` table (assuming that the table is populated)
3. Click on any entry in the table
4. See the flyout with monitor details open
5. See the missing "X" button in the flyout header

**What is the expected behavior?**
The "X" icon should be present in the flyout header to allow user to close the flyout using the regular pattern.

**What is your host/environment?**

- OS: macOS
- Version 12.4
- Plugins Alerting
- Browser Chrome, Firefox, Safari

**Do you have any screenshots?**
<img width="726" alt="Screen Shot 2022-08-04 at 12 37 50 AM" src="https://user-images.githubusercontent.com/105245012/182791486-dd2b1ac3-06fb-48be-9e03-58b0e45cf6d0.png">

**Comment by AWSHurneyt** [comment]
Added these buttons to the `Alerts` and `Findings` flyouts locally, and will be publishing a PR once the tests finish.

**Comment by amsiglan** [comment]
@AWSHurneyt Let's create the PR for this

**Comment by amsiglan** [comment]
Completed
