### ISSUE TITLE
[BUG] Monitors created from backend incorrectly display Schedule when editing Monitor

### ISSUE THREAD

**Issue by qreshi** [opensearch-project/alerting-dashboards-plugin#32]
**Describe the bug**
If a Monitor is created (at least with cron expression, did not check interval behavior) using the backend REST API, when going to the `Edit Monitor` page in the frontend plugin, the `Monitor Schedule` section displays the default of `1 minute interval`. The cron information is actually being stored in the formik object derived from the Monitor object but it isn't the selected default. If the user ends up saving the Monitor without doing anything, the saved Monitor schedule will become the default of 1 minute.

**To Reproduce**
1. Create a Monitor with a cron schedule using the [backend API](https://opensearch.org/docs/monitoring-plugins/alerting/api/#create-monitor)
2. Go to `Monitors` page in the Alerting console
3. Select the Monitor to go to the Monitor details page
4. Select `Edit`
5. Scroll down to `Monitor Schedule`

**Expected behavior**
When creating a Monitor from the backend API, if the Monitor schedule is a cron expression, then default to the `Custom cron expression` display in the `Edit Monitor` page to ensure it can be shown regardless of the expression. May also need to test this with other schedule types to see if they behave correctly.

**Screenshots**
User reported this issue in a [forum question](https://discuss.opendistrocommunity.dev/t/monitors-created-through-api-doesnt-reflect-proper-schedule/6691) which includes screenshots. The user was on the OpenDistro version of Alerting but this behavior has not been altered in OpenSearch and all new issues are being handled here.

**Comment by AWSHurneyt** [comment]
This issue has been resolved with the above PR in the 2.0 release.
