### ISSUE TITLE
[Distribution build failure] Error building on alerting dashboards

### ISSUE THREAD

**Issue by zelinh** [opensearch-project/alerting-dashboards-plugin#341]
**What is the bug?**
`error d3-color@3.1.0: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"`
Seems like we added this package yesterday but it's not compatible with our current node version 10.24.1.
https://github.com/opensearch-project/alerting-dashboards-plugin/blob/be086db815d909908e953b0fe0ee30520dc32f60/package.json#L47
This is blocking our build pipeline right now. 

More log details: https://build.ci.opensearch.org/job/distribution-build-opensearch-dashboards/4138/console

**Comment by lezzago** [comment]
We added this version due to this issue: https://github.com/opensearch-project/alerting-dashboards-plugin/issues/338.
`3.1.0` is the earliest version the issue has been patched.
