### ISSUE TITLE
[BUG] Kibana still listed in repo description

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/alerting-dashboards-plugin#41]
**Describe the bug**
The repo says "OpenSearch Dashboards Kibana Alerting Plugin" - this plugin doesn't run in Kibana, so that should be removed.

**To Reproduce**
1. Go to github repo
2. Look to the right
3. See this:
<img width="299" alt="Screen Shot 2021-08-16 at 3 22 19 PM" src="https://user-images.githubusercontent.com/1152927/129618495-d4c42dba-dbaf-4778-9826-47da616eaf6a.png">

**Expected behavior**
It doesn't mention that other product.

**Plugins**
n/a

**Screenshots**
See above

**Comment by AWSHurneyt** [comment]
Closing this issue as the `About` section has been updated to:
![Screen Shot 2021-11-05 at 9 41 24 AM](https://user-images.githubusercontent.com/79280347/140546814-3111758c-2030-434b-89ef-87c5622ec9fd.png)
