### ISSUE TITLE
[FEATURE] Support multiple data filters through visual editor view in monitor creation page

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/alerting-dashboards-plugin#432]
**Is your feature request related to a problem?**
Support multiple data filters through visual editor view in the monitor creation page.

**What solution would you like?**
All users to have multiple data filters instead of just one. This can still be limited to a number of 10 filters.

**Comment by VigneshOK10** [comment]
more info - https://forum.opensearch.org/t/unable-to-create-monitor-with-multiple-data-filter/11691/3

**Comment by AWSHurneyt** [comment]
Request to update the documentation page to reflect this change, and that documents must match all of the filters in order to be included in the monitor execution results.
https://github.com/opensearch-project/documentation-website/issues/3546

**Comment by AWSHurneyt** [comment]
Closing this issue as this enhancement made it into the 2.7 release.
