### ISSUE TITLE
[BUG] Trigger not producing alert when query is specified

### ISSUE THREAD

**Issue by uroskarama** [opensearch-project/alerting-dashboards-plugin#448]
**What is the bug?**
When creating a Per Document monitor, and adding a Trigger with the query specified, the trigger is not triggered (Alerts are not produced).

**How can one reproduce the bug?**
1. Create a monitor with a query named query1.
2. Add new trigger to monitor, and in Trigger conditions dropdown select query1. 
3. In Dev tools insert a document that matches query1.
4. Check Document findings for the monitor - document is found, but alert is not created.

**What is the expected behavior?**
Alerts are supposed to be produced by the trigger when query is set as condition.

**What is your host/environment?**
Opensearch Cluster Version - 2.4.0
Opensearch Dashboard Version - 2.4.0

**Do you have any screenshots?**
![Screenshot from 2023-01-18 17-34-29](https://user-images.githubusercontent.com/117112198/213239276-0a2871d4-ccbe-4030-853b-cadc8fd4b8aa.png)
![image](https://user-images.githubusercontent.com/117112198/213239328-9b7cf019-f104-4ba3-bc3c-47bcd5bffb93.png)

**Do you have any additional context?**
First screenshot is the suspected issue - for some reason the query is negated "!query[name=testq]"/
Second is the suggested fix for the issue in the code.

**Comment by lezzago** [comment]
Were findings created, but not alerts? When choosing the dropdown for the trigger, was it specified to do a `not` of query, `testq`?

**Comment by AWSHurneyt** [comment]
Closing this issue as the bug fix was release with v2.7, and backported to older versions. Please feel free to reopen if you're still experiencing the problem, though.
