### ISSUE TITLE
[BUG] Blank Page when Editing Monitor with SNS Integration

### ISSUE THREAD

**Issue by kavilla** [opensearch-project/alerting-dashboards-plugin#529]
@michaelact commented on [Thu Apr 13 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3840)

**Describe the bug**
Blank Page when Editing Monitor with SNS Integration

**To Reproduce**
1. Go to Alerting > Monitor > Create Monitor > Add Trigger
2. Click on 'Select channel to notify' dropdown
3. Choose one of SNS channel
4. Blank page and see error in console.

**Expected behavior**
Should be able to edit the monitor.

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Plugins**
Opensearch Dashboard:
```
$ ls plugins/
alertingDashboards/          mlCommonsDashboards/         searchRelevanceDashboards/
anomalyDetectionDashboards/  notificationsDashboards/     securityAnalyticsDashboards/
customImportMapDashboards/   observabilityDashboards/     securityDashboards/
ganttChartDashboards/        queryWorkbenchDashboards/
indexManagementDashboards/   reportsDashboards/
```

Opensearch Cluster:
```
$ ls plugins/
opensearch-alerting                   opensearch-neural-search
opensearch-anomaly-detection          opensearch-notifications
opensearch-asynchronous-search        opensearch-notifications-core
opensearch-cross-cluster-replication  opensearch-observability
opensearch-geospatial                 opensearch-performance-analyzer
opensearch-index-management           opensearch-reports-scheduler
opensearch-job-scheduler              opensearch-security
opensearch-knn                        opensearch-security-analytics
opensearch-ml                         opensearch-sql
```

**Screenshots**

<img width="920" alt="image" src="https://user-images.githubusercontent.com/86778470/231703339-939d4649-efe2-4ecb-937c-70ede94ab5bd.png">

**Host/Environment (please complete the following information):**
 - OS: Windows 11
 - Browser and version: Microsoft Edge 112

---

@joshuarrrr commented on [Thu Apr 13 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3840#issuecomment-1507562960)

@opensearch-project/triage Please transfer to https://github.com/opensearch-project/alerting-dashboards-plugin

---

@michaelact commented on [Thu Apr 13 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3840#issuecomment-1507802394)

> @opensearch-project/triage Please transfer to https://github.com/opensearch-project/alerting-dashboards-plugin

How?

---

@joshuarrrr commented on [Fri Apr 14 2023](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3840#issuecomment-1508976422)

@opensearch-project/triage is a group of admins with permissions to transfer issues between Opensearch project repositories. I don't have the permissions to transfer it myself.

**Comment by Anarhyst266** [comment]
Faced this also on 2.4.1 from MacOS 13.3.1, Safari 16.4 and Chrome 112.0.5615.49

**Comment by Anarhyst266** [comment]
Any updates there? It's blocking us from normally using SNS as notification channel

**Comment by Anarhyst266** [comment]
Still broken in 2.8.0

**Comment by magnussuther** [comment]
As far as I can tell, https://github.com/opensearch-project/alerting-dashboards-plugin/commit/1c7239f80ca44b3e5dd429ebfada035cbb88a4f6 will fix this bug.

**Comment by lezzago** [comment]
Closing as this PR has been merged: https://github.com/opensearch-project/alerting-dashboards-plugin/pull/743
