### ISSUE TITLE
[FEATURE] Add composite monitor type

### ISSUE THREAD

**Issue by jovancacvetkovic** [opensearch-project/alerting-dashboards-plugin#573]
**Is your feature request related to a problem?**
Add composite monitor type

**What solution would you like?**
Add composite monitor type

**Do you have any additional context?**
![image](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/28289071/8d7a835f-e1ce-4320-9f5b-8824498c6a4a)
![image](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/28289071/0427e8dd-2806-481c-b76d-f686402ed875)
![image](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/28289071/0f1d1cf1-7098-46fe-a56e-0b2f8bab6a1d)

**Comment by AWSHurneyt** [comment]
Closing as composite monitors were launched in v2.9
https://github.com/opensearch-project/alerting-dashboards-plugin/pull/679
