### ISSUE TITLE
[BUG] Not able to add data filters when creating a monitor

### ISSUE THREAD

**Issue by matthias-prog** [opensearch-project/alerting-dashboards-plugin#590]
**What is the bug?**
Users are not able to save/add data filters when creating a per query monitor with the visual editor.

**How can one reproduce the bug?**
1. Go to 'Alerting' -> 'Monitors' -> 'Create Monitor'
2. Leave 'Per query monitor' and 'Visual editor' as is
3. Add any index and select a Time Field for it
4. Click on 'Add filter' under 'Data filter'
5. Try to add a Data Filter -> no way to that, nothing happens when you press enter, when you click outside the popup for creating the filter the pop-up just vanishes and the filter does not get added

**What is the expected behavior?**
Clicking outside the pop-up adds the filter or clicking a "save" button on the pop-up adds the filter

**What is your host/environment?**
 - OS: Red Hat Enterprise Linux release 8.8 (Ootpa) on amd64
 - Docker Image opensearchproject/opensearch:2.8.0 and opensearchproject/opensearch-dashboards:2.8.0 using podman 4.4.1 
 - Google Chrome Version 114.0.5735.199 64-bit

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/66998325/638624dc-0d26-4636-aaff-af26025e7912)

**Do you have any additional context?**
When trying to create the filter the browser console logs "Unknown query operator detected: is" or "Unknown query operator detected: is_less" 
The filter can be added if you click once on the "entry" 
![image](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/66998325/5798490e-68cf-48ca-83c9-77b6e36043b7)
which leads to the pop-up not vanishing anymore if click outside it. If you now switch to "anomaly detector" and then back to "visual editor" the filter is added, but this is not a usable workaround for our users.

**Comment by mattmooree** [comment]
This is also reproducible in AWS OpenSearch 2.7.0 (OpenSearch_2_7_R20230706 (latest))

**Comment by thomass4t** [comment]
Is there any workaround for this issue?
Also editing shows the same effect. Filter vanishes when closing popup.

**Comment by AWSHurneyt** [comment]
Hi @thomass4t,
I added a comment with a workaround using the `extraction query editor` here https://github.com/opensearch-project/alerting-dashboards-plugin/issues/558#issuecomment-1654549583

**Comment by AWSHurneyt** [comment]
Closing this issue as the fix in PR https://github.com/opensearch-project/alerting-dashboards-plugin/pull/574 has been merged and released with 2.9. Please feel free to reopen this issue if this issue persists.
