### ISSUE TITLE
[BUG] UI drops focus when configuring a monitor action

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/alerting-dashboards-plugin#785]
**What is the bug?**
On latest v2.11, when configuring an action on any monitor, the fields "Message subject" and "Message" accept only one character before they lose focus. To write a sentence you need to strike a letter, click on the field again, strike next letter, etc. This bug did not exist on v2.10.

**How can one reproduce the bug?**
1. Go to playground.opensearch.org and edit the [sample_cluster_metrics_nodes_stats_monitor](https://playground.opensearch.org/app/alerting#/monitors/6vaSOosBa5CNl5BaR20Q?action=update-monitor)
2. Click on "sample_node_trigger"
3. Click on "Add action"
4. Give it any name you like
5. Try to edit "Message subject" or " Message" fields. You'll notice that each time you enter a character the UI loses focus.
6. "Enable action throttling" and try to enter a value on "Throttle actions to only trigger every". Same thing happens.

**What is the expected behavior?**
The fields "Message subject", "Message" and "Throttle actions to only trigger every" not to lose focus while editing.

**What is your host/environment?**
- I'm on macOS, used Firefox, Safari and Chrome browser
- Experienced the problem on the official opensearch playground cluster and on other local clusters

**Comment by adamdepollo** [comment]
Commenting for support -- this behavior is EXTREMELY annoying.

**Comment by ict-one-nl** [comment]
Confirmed. I'm typing in text edit and pasting for now..

https://github.com/opensearch-project/alerting-dashboards-plugin/assets/2643715/c1412f1c-6b1c-4d3b-bc04-84f27dd7d406

**Comment by AWSHurneyt** [comment]
@spapadop Thanks for calling out this bug! 

We have a fix at the moment that has been merged to our 2.11 branch, and will be included in a future patch. For now I'll close this issue as we're tracking the fix in issue https://github.com/opensearch-project/alerting-dashboards-plugin/issues/853
