### ISSUE TITLE
[BUG] Per bucket and per document trigger message preview isn't populating with context info

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/alerting-dashboards-plugin#791]
**What is the bug?**
The `Preview message` box isn't populating with the context information for the configured triggers for `Per bucket`, and `Per document` monitors. 

This bug **does not** seem to impact `Per query` and `Per cluster metrics` monitors. `Composite monitors` do not currently support configuring a notification message via the UI, so that monitor type also isn't impacted at the moment.

**How can one reproduce the bug?**
1. Go to create monitor page
2. Define a `per bucket` or `per document` with a trigger, and ensure the trigger has a name
3. Add an action, and display the `Preview message` box
4. The `trigger name` and `severity` values will be blank

**What is the expected behavior?**

**What is your host/environment?**
 - OS: macOS
 - Version: 13.4.1 (22F82)
 - Plugins: alerting, and alerting dashboards

**Do you have any screenshots?**
In this screenshot, we can see that the `trigger name` and `severity` values are blank in the message preview box despite the trigger having a name and severity configured.
![Screenshot 2023-11-03 at 11 55 11 AM](https://github.com/opensearch-project/alerting-dashboards-plugin/assets/79280347/f0871d02-c655-4dab-abfb-32f568281d4c)

**Comment by tanupa** [comment]
I can assign myself to this one!

**Comment by AWSHurneyt** [comment]
Closing as the fix has been merged and released.
