### ISSUE TITLE
[BUG] "Group by"/aggregations selections in visual editor reset when editing monitor

### ISSUE THREAD

**Issue by AWSHurneyt** [opensearch-project/alerting-dashboards-plugin#816]
**What is the bug?**
In the visual editor for the create monitor, users can select `Group by`/`aggregations` options. Those selections are reset to blank when editing a monitor.

This bug just impacts the UI. If you use the SearchMonitor API, the `Group by`/`aggregations` selections will be present in the monitor query; so the monitor's execution will reflect the those selections.

**How can one reproduce the bug?**
1. Go to create monitor page
2. Select the `Per query"`, or `Per bucket` monitor type
3. Configure the monitor using the `Visual editor` UI
4. Add a `Group by` option (note that, as of v2.11, the `Group by` dropdown will only populate with fields that have the type `keyword`
5. Create the monitor
6. Once created, edit the monitor using the visual editor
7. The `Group by` field will be blank

**What is the expected behavior?**

**What is your host/environment?**
 - OS: macOS
 - Version: 13.4.1 (22F82)
 - Plugins: v2.11 alerting and alerting dashboards

**Comment by AWSHurneyt** [comment]
Related issue https://github.com/opensearch-project/alerting-dashboards-plugin/issues/818

**Comment by StefanStroebel** [comment]
I just tested 2.11.1 and this issue is still occuring. The release docs said it was fixed.

**Comment by yoicomment** [comment]
> I just tested 2.11.1 and this issue is still occuring. The release docs said it was fixed.

Yes, having the same problem in 2.11.1

**Comment by amsiglan** [comment]
@StefanStroebel @ghost Looks like we couldn't get this merged in time for 2.11.1
The fix is available in 2.12 and up
and it has been backported to the 2.11, 2.10 and 2.09 branches so whenever we have the next patch release for these versions, it will be available at that point.

Closing the issue since the fix has been merged.
