### ISSUE TITLE
[BUG] Bucket level monitor alerts on Alerts dashboard doesnt display group by (bucket) field name and bucket value

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/alerting-dashboards-plugin#817]
**What is the bug?**
A clear and concise description of the bug.

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by AWSHurneyt** [comment]
Closing as the fix has been merged and released.

**Comment by yoicomment** [comment]
> Closing as the fix has been merged and released.

Still having the problem with 2.11.1
