### ISSUE TITLE
[BUG] Message input text area loses focus on keydown when adding trigger in a monitor

### ISSUE THREAD

**Issue by amsiglan** [opensearch-project/alerting-dashboards-plugin#853]
**What is the bug?**
When user is trying to update the message template inside trigger action, the text area control loses focus immediately after keydown.

**How can one reproduce the bug?**
1. Go to Create detector page
2. Ensure Notification plugin is installed and there is a notification channel created
3. Add trigger condition. It will show the default Message template
<img width="1507" alt="image" src="https://github.com/opensearch-project/alerting-dashboards-plugin/assets/114732919/af3d5c83-6bcb-4d7f-a474-76bb2067c99b">
4. Try to update the message template, the input box immediately loses focus

**What is the expected behavior?**
The input text area should not lose focus

**What is your host/environment?**
 - Alerting 2.11

**Do you have any screenshots?**
N/A

**Do you have any additional context?**
Add any other context about the problem.

**Comment by AWSHurneyt** [comment]
Closing this issue as the fix has been merged and backported, and will be included in future patches.
