### ISSUE TITLE
[BUG] Alerting UI allows only 1 character at a time

### ISSUE THREAD

**Issue by jowg-amazon** [opensearch-project/alerting-dashboards-plugin#863]
**What is the bug?**
When creating a trigger, the `message subject` and the `message` field only allows for one UI character at a time. 

**How can one reproduce the bug?**
1. Create an alerting monitor
2. Create a trigger and define an action
3. Modify the `message subject` and `message` section

**What is the expected behavior?**

**What is your host/environment?**
 - OS: 2.11

**Do you have any screenshots?**
Attached a video below of the bug.
https://github.com/opensearch-project/alerting-dashboards-plugin/assets/109310487/a98cfd22-b396-47c7-ad5c-38a4bd26ced8

**Do you have any additional context?**
Add any other context about the problem.

**Comment by AWSHurneyt** [comment]
Closing this issue in favor of https://github.com/opensearch-project/alerting-dashboards-plugin/issues/853 which was fixed with PR https://github.com/opensearch-project/alerting-dashboards-plugin/pull/854.
