### ISSUE TITLE
[BUG] group by parameter not adding extra field in alerts table

### ISSUE THREAD

**Issue by ghost** [opensearch-project/alerting-dashboards-plugin#883]
**What is the bug?**
group by parameter in per bucket monitor: no extra field in alerts table added for group by parameter.

**How can one reproduce the bug?**
1. Attempt to create monitor
2. Add group by parameter
3. Create monitor
4. See in alerts table that no extra field (group by field) is added to alerts table

**What is the expected behavior?**
the group by paramter should be added to alerts table.

**What is your host/environment?**
 - docker
 - 2.11.1
 - Alerting and dashboard alerting

This worked in version 2.8.0 but does not work in 2.9.0, 2.10.0, 2.11.0 and 2.11.1
Look at forum thread concerning this bug

https://forum.opensearch.org/t/alerts-and-aggregation-name/7762/11

**Comment by amsiglan** [comment]
Fix has been merged in 2.11 and will be available when we have 2.11.2 patch release

Backport PRs for 2.9 and 2.10
- https://github.com/opensearch-project/alerting-dashboards-plugin/pull/837
- https://github.com/opensearch-project/alerting-dashboards-plugin/pull/835

**Comment by amsiglan** [comment]
Closing the issue since the fixes have been merged in 2.9, 2.10 and 2.11 branches. These will get rolled out as part of next patch release
