### ISSUE TITLE
[Review Needed] Review the RFC to introduce application level configuration at OSD

### ISSUE THREAD

**Issue by tianleh** [opensearch-project/alerting-dashboards-plugin#887]
Hi, team

Please review this RFC introduce application level configuration at OSD https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5796

Once you review the proposal and raise concern if any, then you can resolve this issue.

**Comment by dblock** [comment]
Looks like the RFC was reviewed and closed.

Catch All Triage - [1](https://github.com/dblock) [2](https://github.com/krisfreedain) [3](https://github.com/gkamat) [4](https://github.com/andrross) [5](https://github.com/getsaurabh02)
